name: Publish Packages

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'src/Core.Common.LocalizableString.Tests/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test with the dotnet CLI
      run: dotnet test src/Core.Common.LocalizableString.Tests/Core.Common.LocalizableString.Tests.csproj --no-restore --verbosity normal
    - name: Publish to Nuget
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
          # Filepath of the project to be packaged, relative to root of repository
          PROJECT_FILE_PATH: src/Core.Common.LocalizableString/Core.Common.LocalizableString.csproj
          # API key to authenticate with NuGet server
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          # Flag to toggle pushing symbols along with nuget package to the server, disabled by default
          INCLUDE_SYMBOLS: true
