name: Publish Packages

on:
    workflow_run:
        workflows: ["Run Tests By Logic", "Update README", "Update LICENSE"]
        branches: [ "main" ]
        types: 
            - completed

jobs:
  build-publish:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore src/Core.Common.LocalizableString/Core.Common.LocalizableString.csproj
    - name: Build
      run: dotnet build src/Core.Common.LocalizableString/Core.Common.LocalizableString.csproj --configuration Release --no-restore
    - name: Publish to Nuget
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
          # Filepath of the project to be packaged, relative to root of repository
          PROJECT_FILE_PATH: src/Core.Common.LocalizableString/Core.Common.LocalizableString.csproj
          # API key to authenticate with NuGet server
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          # Flag to toggle pushing symbols along with nuget package to the server, disabled by default
          INCLUDE_SYMBOLS: true
